# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: r53-ddns
# app and org for use with dashboard.serverless.com
app: r53-ddns-app
org: ryo614

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: python3.8
  deploymentBucket:
    name: serverless-gogobike-deployment
  versionFunctions: false
  apiKeys:
    - r53DDns
  apiName: r53ddns

# you can overwrite defaults here
#  stage: dev
  region: ap-northeast-1
  stage: ${opt:stage, 'dev'}

# you can add statements to the Lambda function's IAM Role here
  iamRoleStatements:
    - Sid: "GetRoute53"
      Effect: "Allow"
      Action:
        - "route53:ListHostedZonesByName"
        - "route53:ListHostedZones"
        - "route53:ListResourceRecordSets"
        - "route53:ChangeResourceRecordSets"
      Resource: "*"

# you can define service wide environment variables here
#  environment:
#    variable1: value1

functions:
  hello:
    handler: handler.hello
    timeout: 30
#    The following are a few example events you can configure
#    NOTE: Please make sure to change your handler code to work with those events
#    Check the event documentation for details
    events:
      - http:
          path: test
          method: post
          private: true
          integration: lambda
    environment: ${self:custom.environment.${self:provider.stage}}

#    Define function environment variables here
#    environment:
#      variable2: value2
custom:
  environment:
    dev: ${file(./env/dev.yml)}
    prod: ${file(./env/prod.yml)}
